name: Check
on:
  push:
    branches: ['**']
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Wait for MongoDB to be ready
        run: |
          echo "Checking if MongoDB is ready..."
          sleep 15  # Задержка перед проверкой
          if mongo --host localhost --port 27017 --eval "print('MongoDB is ready')" &>/dev/null; then
            echo "MongoDB is ready"
          else
            echo "MongoDB is not ready yet"
            exit 1
          fi
        shell: bash

      - name: Run tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
          JWT_EXPIRY: ${{ secrets.JWT_EXPIRY }}
          REFRESH_TOKEN_EXPIRY: ${{ secrets.REFRESH_TOKEN_EXPIRY }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: npm test
